name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest #Good for Industry level working 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # This action checks out your repository under $GITHUB_WORKSPACE, so your workflow can access it.

    - name: Set up Python
      uses: actions/setup-python@v2 # This action sets up a Python environment for use in actions.
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest streamlit

    - name: Run tests 
      run: |
        pytest _test.py